### ISSUE TITLE
Models folder not found

### ISSUE THREAD

**Issue by kigenchesire** [thisisishara/llm-response-bot#1]
I have tried running the model but i get the error that the models folder is not found

**Comment by thisisishara** [comment]
> I have tried running the model but i get the error that the models folder is not found

Usually, rasa models are not committed to git repos since they can be somewhat large in size. Specifically in this case, training happens when the [Docker image of Rasa](https://github.com/thisisishara/llm-response-bot/blob/d2d53e3b27ed283e48d84361454c1be4bd141dd2/Dockerfile#L11) is being build. You just have to run `docker compose up -d` in the project root, that's it.

**Comment by thisisishara** [comment]
I'm going to close issue since the above instructions should help you to run the bot. Feel free to re-open the issue if you come across further issues related to this. Cheers!
